services:
  etl_service:
    build: .  
    container_name: etl-mts-test
    ports:
      - "8080:8080" 
    volumes:
      - ./data:/data  
      - ./logs:/logs 
      - ./scripts:/scripts 
      - ./output:/output
    environment:
      - LOG_FILE=/logs/etl.log
    command: sh -c "python scripts/etl.py && sqlite_web --host 0.0.0.0 --port 8080 /data/transactions.db"

